### ISSUE TITLE
VAC-Bypass.dll VIRUS SCAN

### ISSUE THREAD

**Issue by rafalohaki** [ByMynix/CouInjector#1]
This one is from Couinjector
https://analyze.intezer.com/analyses/eef8a1df-52d2-46f8-8073-c9e31b37e71b/genetic-analysis

this one is original
https://analyze.intezer.com/analyses/28ad656c-d967-4340-b1f2-95a64690c4c7/genetic-analysis

why there so much diff if they are the same dlls(i mean the same function from daniel)?

**Comment by ByMynix** [comment]
That's strange to see. It is the same function, you can see that even in the detection. But it only seems to be like that on intezer. In virustotal it has the same detections:

[CouInjector VAC-ByPass](https://www.virustotal.com/gui/file/01c87b4c68050f9bf7ee9d16fc0884b272c1ee04497f77c7e56beaa486e6de1f?nocache=1)

[daniel's VAC-ByPass](https://www.virustotal.com/gui/file/96ca62152d371f39f631528098f241f0ecedadf4d09992d5ff8d29136487e64a?nocache=1)

**Comment by rafalohaki** [comment]
> That's strange to see. It is the same function, you can see that even in the detection. But it only seems to be like that on intezer. In virustotal it has a similar number of detections, but also a few differences:
> 
> [CouInjector VAC-ByPass](https://www.virustotal.com/gui/file/01c87b4c68050f9bf7ee9d16fc0884b272c1ee04497f77c7e56beaa486e6de1f?nocache=1)
> 
> [daniel's VAC-ByPass](https://www.virustotal.com/gui/file/96ca62152d371f39f631528098f241f0ecedadf4d09992d5ff8d29136487e64a?nocache=1)

as u can see, the original one doesnt have any behaviour
