### ISSUE TITLE
cou broken?

### ISSUE THREAD

**Issue by BegleitPanzer** [ByMynix/CouInjector#10]
![image](https://github.com/ByMynix/CouInjector/assets/134264166/7c445b69-7f2c-4656-8ff9-93be09f8788f)

**Comment by ByMynix** [comment]
> ![image](https://user-images.githubusercontent.com/134264166/263490765-7c445b69-7f2c-4656-8ff9-93be09f8788f.png)

Is some user problem. Already known. So far I have not been able to identify it correctly. On a normal PC this problem does not occur (so for 95% users). Maybe it is related to the dependencies in the local .net framework. Maybe it also helps to check the antivirus exception again and re-download or build CouInjector in Visual Studio.

**Comment by BegleitPanzer** [comment]
I suspect it has something to do with FACEIT AC

**Comment by ByMynix** [comment]
> I suspect it has something to do with FACEIT AC
> 
> same issue with neutro, couldn't inject when FACEIT was running

Good to know, thanks for the information. That could be good, which is why it applies to only a few where this error happens. Since FaceIT is also running at the administration level.
