### ISSUE TITLE
it giving error on source code

### ISSUE THREAD

**Issue by N2K2021** [ByMynix/CouInjector#3]
it says system.object cant found pls how can i fix it

**Comment by ByMynix** [comment]
> it says system.object cant found pls how can i fix it

Can you explain the problem further? Is it just the System.Object not being found or are there multiple errors?

**Comment by N2K2021** [comment]
> > it says system.object cant found pls how can i fix it
> 
> Can you explain the problem further? Is it just the System.Object not being found or are there multiple errors?

600 + errors

**Comment by N2K2021** [comment]
error bcz of references

**Comment by ByMynix** [comment]
> > > it says system.object cant found pls how can i fix it
> > 
> > 
> > Can you explain the problem further? Is it just the System.Object not being found or are there multiple errors?
> 
> 600 + errors

In the "Build" tab, click on "Rebuild CouInjector" and when completed click on "Rebuild Solution", that should fix the problem.

**Comment by N2K2021** [comment]
> > > > it says system.object cant found pls how can i fix it
> > > 
> > > 
> > > Can you explain the problem further? Is it just the System.Object not being found or are there multiple errors?
> > 
> > 
> > 600 + errors
> 
> In the "Build" tab, click on "Rebuild CouInjector" and when completed click on "Rebuild Solution", that should fix the problem.

failed

**Comment by ByMynix** [comment]
> > > > > it says system.object cant found pls how can i fix it
> > > > 
> > > > 
> > > > Can you explain the problem further? Is it just the System.Object not being found or are there multiple errors?
> > > 
> > > 
> > > 600 + errors
> > 
> > 
> > In the "Build" tab, click on "Rebuild CouInjector" and when completed click on "Rebuild Solution", that should fix the problem.
> 
> failed

Okay, can we talk this on my [discord server](https://dsc.gg/bymynixde)? For others who have the same problem, I would send in the solution here afterwards.
