### ISSUE TITLE
Windowns 11 Injection

### ISSUE THREAD

**Issue by Lorenzobettega** [ByMynix/CouInjector#6]
It is not working at Windowns 11

**Comment by ByMynix** [comment]
Hey Lorenzobettega, how do you mean it's not working for Windows 11? CouInjector was developed for Windows 10/11

**Comment by Lorenzobettega** [comment]
The Injection is not working, same as SazzInjector, called that inject, but any hack didn't work.

**Comment by ByMynix** [comment]
> The Injection is not working, same as SazzInjector, called that inject, but any hack didn't work.

Try installing the latest C++ redistributables in x86 and x64 : [latest-supported-vc-redist ](https://learn.microsoft.com/cpp/windows/latest-supported-vc-redist?view=msvc-170)
If CouInjector also states that the injection was successful it will be, only there seems to be something wrong with the cheat itself, what it is exactly I can't say for sure, but the just mentioned is a regular problem.
