### ISSUE TITLE
Cou game/vac bans

### ISSUE THREAD

**Issue by fanat1cc** [ByMynix/CouInjector#8]
I don't use the vac bypass on cou for many reasons but
In the passed week 2 of my accs got game than a day or 2 later got vacced.

This could be my cheat (heavly modified osiris) or cou injector.

I will continue testing.

**Comment by ByMynix** [comment]
> I don't use the vac bypass on cou for many reasons but In the passed week 2 of my accs got game than a day or 2 later got vacced.
> 
> This could be my cheat (heavly modified osiris) or cou injector.
> 
> I will continue testing.

Hey fanat1cc, If the injection is detected, you should get a direct VAC ban (as I know). So I don't think it's the injection. I think it is most likely due to the modified Osiris, but feel free to share what your tests showed.

**Comment by ByMynix** [comment]
-No answer

**Comment by ByMynix** [comment]
> I forgot to post a answer, however I can say for sure that cou is still safe and that it was infact that my cheat had detected features Enabled

Thank you for the subsequent answer. That's good to know! So I know that everything still works great.
